### ISSUE TITLE
Registrierungs Seite Design & Geburtsdatum Check

### ISSUE THREAD

**Issue by RoseFlunder** [RoseFlunder/SWE3-MoneyDouble#11]
Gleiches Design wie Login Seite.
Ergänzen um Feld für Geburtstag mit Validator, dass Benutzer volljährig sein muss.
Benutzer Entity hat auch ein Feld "geburtsdatum".

**Comment by RoseFlunder** [comment]
Validator ergänzen

**Comment by Triforce2II** [comment]
fertig
